---
- name: install webext-privacy-badger
  package: name=webext-privacy-badger state=latest

- name: install webext-noscript
  package: name=webext-noscript state=latest

- name: install webext-https-everywhere
  package: name=webext-https-everywhere state=latest

- name: install ufw
  package: name=ufw state=latest

## TODO: Unclear if "deny all inbound by default" actually works;
## test this.
- name: enable ufw and deny all inbound by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: turn ufw logging on
  ufw:
    logging: on

- name: uninstall avahi
  package: name=avahi-daemon state=absent

- name: uninstall minissdpd
  package: name=minissdpd state=absent

- name: install apparmor
  package: name=apparmor state=latest

- name: install apparmor-profiles
  package: name=apparmor-profiles state=latest

- name: install apparmor-profiles-extra
  package: name=apparmor-profiles-extra state=latest
